In [18]:
#Linear SVM classification.
#Well this works well with linearly separable datasets i.e datasets that can be separated by a straight line.
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 2).astype(np.float64) # Iris-Virginica
svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVC(C=1, loss="hinge", dual= "auto")),])
svm_clf.fit(X, y)


Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, dual='auto', loss='hinge'))])

In [19]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

In [20]:
#Nonlinear SVM Classification, Well data that are not linearly separable can often be made so by adding more features,
#using the polynomial scaler. 
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
polynomial_svm_clf = Pipeline([
 ("poly_features", PolynomialFeatures(degree=3)),
 ("scaler", StandardScaler()),
 ("svm_clf", LinearSVC(C=10, loss="hinge", dual = "auto"))
 ])
polynomial_svm_clf.fit(X, y)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf', LinearSVC(C=10, dual='auto', loss='hinge'))])

In [21]:
polynomial_svm_clf.predict([[5.5, 1.7]])

array([1.])

In [22]:
#Polynomial Kernel: 
#It makes it possible to get the same result as if you added many polynomial features, even with very high degree polynomials, 
#without actually having to add them. 
#So there is no combinatorial explosion of the number of features since you don’t actually add any features. 


from sklearn.svm import SVC
poly_kernel_svm_clf = Pipeline([
 ("scaler", StandardScaler()),
 ("svm_clf", SVC(kernel="poly", degree=3, coef0=1, C=5))
 ])
poly_kernel_svm_clf.fit(X, y)
#This gives us the goodnes of polynomial features but none of the drawbacks.

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly'))])

In [23]:
poly_kernel_svm_clf.predict([[5.5, 1.7]])

array([1.])

In [24]:
#Adding Similarity Features
#Another technique to tackle nonlinear problems is to add features computed using a
#similarity function that measures how much each instance resembles a particular landmark.

rbf_kernel_svm_clf = Pipeline([
 ("scaler", StandardScaler()),
 ("svm_clf", SVC(kernel="rbf", gamma=5, C=1000))
 ])
rbf_kernel_svm_clf.fit(X, y)


Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=1000, gamma=5))])

In [25]:
rbf_kernel_svm_clf.predict([[5.5, 1.7]])

array([1.])

In [26]:
#SVM can also be used for regression.
from sklearn.svm import LinearSVR
svm_reg = LinearSVR(epsilon=1.5)
svm_reg.fit(X, y)


C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


LinearSVR(epsilon=1.5)

In [27]:
svm_reg.predict([[5.5, 1.7]])

array([0.])

In [28]:
#The SVR class is the regression equivalent of the SVC class, and the LinearSVR class is the regression equivalent of the LinearSVC class. 
from sklearn.svm import SVR
svm_poly_reg = SVR(kernel="poly", degree=2, C=0.01, epsilon=0.1)
svm_poly_reg.fit(X, y)

SVR(C=0.01, degree=2, kernel='poly')

In [29]:
svm_poly_reg.predict([[5.5, 1.7]])

array([0.70591148])